### ISSUE TITLE
Ensure https is used in the API call

### ISSUE THREAD

**Issue by nuchi** [thorn-oss/perception#1]
If a user passes an `http://` url to the `SaferMatcher`, their username/password or API key will be sent in the clear. Adding a check to ensure they're using an `https://` url would prevent them from accidentally sending credentials over the network in clear-text.

(I'd happily open a PR)

**Comment by davidrs** [comment]
@nuchi  great catch. If you could send a PR that would be amazing. Thanks for the contribution :)
