### ISSUE TITLE
Facebook's PDQ Hash

### ISSUE THREAD

**Issue by victorfunch** [thorn-oss/perception#25]
Hi there,

In the README you state that you support Facebook's PDQ Hash with perception.hashers.PDQ. However, this is not included/or not working in your current version.

Are you working on implementing it again or is it history? 

Best,
Victor

**Comment by BrandonKMLee** [comment]
Please check https://github.com/thorn-oss/perception/blob/main/perception/hashers/image/pdq.py

**Comment by faustomorales** [comment]
To use `pdqhash` you need to install the separate `pdqhash` package. So if you do` pip install pdqhash`, you should be all set.

**Comment by LucioBonetto** [comment]
Thank you. That solved everything.
